import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { ResumeData } from '@/types/resume';
import { generateLatexFromResume, validateLatexSyntax } from '@/utils/latexGenerator';
import { useToast } from '@/hooks/use-toast';
import { FileText, ExternalLink, Eye, EyeOff } from 'lucide-react';

interface OverleafExportProps {
  resumeData: ResumeData;
}

export function OverleafExport({ resumeData }: OverleafExportProps) {
  const [showLatexPreview, setShowLatexPreview] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const exportToOverleaf = async () => {
    setIsExporting(true);
    
    try {
      // Generate LaTeX content from resume data
      const latexContent = generateLatexFromResume(resumeData);
      
      // Validate LaTeX syntax
      const validation = validateLatexSyntax(latexContent);
      
      if (!validation.isValid) {
        toast({
          title: "LaTeX Validation Error",
          description: `Please fix the following issues: ${validation.errors.join(', ')}`,
          variant: "destructive",
        });
        setIsExporting(false);
        return;
      }

      // Basic validation - check if essential fields are filled
      if (!resumeData.personalInfo.fullName || !resumeData.personalInfo.email) {
        toast({
          title: "Incomplete Resume",
          description: "Please fill in at least your full name and email before exporting.",
          variant: "destructive",
        });
        setIsExporting(false);
        return;
      }

      // Convert Windows newlines to Unix newlines for better compatibility
      const normalizedLatex = latexContent.replace(/\r\n/g, '\n');
      
      // URL-encode the LaTeX content
      const encodedContent = encodeURIComponent(normalizedLatex);

      // Create a hidden form to POST to Overleaf
      const form = document.createElement('form');
      form.action = 'https://www.overleaf.com/docs';
      form.method = 'post';
      form.target = '_blank';
      form.style.display = 'none';

      // Add the encoded LaTeX content
      const snipInput = document.createElement('input');
      snipInput.type = 'hidden';
      snipInput.name = 'encoded_snip';
      snipInput.value = encodedContent;
      form.appendChild(snipInput);

      // Optional: Specify TeX engine (pdflatex is default)
      const engineInput = document.createElement('input');
      engineInput.type = 'hidden';
      engineInput.name = 'engine';
      engineInput.value = 'pdflatex';
      form.appendChild(engineInput);

      // Add welcome comment customization
      const commentInput = document.createElement('input');
      commentInput.type = 'hidden';
      commentInput.name = 'comment';
      commentInput.value = 'Generated by Professional Resume Builder - Edit and compile in Overleaf';
      form.appendChild(commentInput);

      // Append form to body and submit
      document.body.appendChild(form);
      form.submit();
      document.body.removeChild(form);

      toast({
        title: "Export Successful!",
        description: "Your resume has been opened in Overleaf. You can now edit and compile it to PDF.",
      });

    } catch (error) {
      console.error('Error exporting to Overleaf:', error);
      toast({
        title: "Export Failed",
        description: "There was an error exporting your resume. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsExporting(false);
    }
  };

  const latexContent = generateLatexFromResume(resumeData);

  return (
    <Card className="shadow-large">
      <CardHeader className="bg-gradient-primary text-primary-foreground">
        <CardTitle className="flex items-center gap-2">
          <FileText className="w-5 h-5" />
          Export to Overleaf
        </CardTitle>
        <p className="text-primary-foreground/80 text-sm">
          Generate and export your resume as a professional LaTeX document
        </p>
      </CardHeader>
      <CardContent className="p-6 space-y-4">
        {/* Export Button */}
        <div className="text-center">
          <Button
            onClick={exportToOverleaf}
            variant="export"
            size="lg"
            disabled={isExporting}
            className="w-full md:w-auto"
          >
            {isExporting ? (
              "Preparing Export..."
            ) : (
              <>
                <ExternalLink className="w-5 h-5" />
                Open in Overleaf
              </>
            )}
          </Button>
          <p className="text-sm text-muted-foreground mt-2">
            This will open your resume in Overleaf where you can edit and compile it to PDF
          </p>
        </div>

        {/* LaTeX Preview Toggle */}
        <div className="border-t pt-4">
          <Button
            onClick={() => setShowLatexPreview(!showLatexPreview)}
            variant="outline"
            className="w-full"
          >
            {showLatexPreview ? (
              <>
                <EyeOff className="w-4 h-4" />
                Hide LaTeX Preview
              </>
            ) : (
              <>
                <Eye className="w-4 h-4" />
                Show LaTeX Preview
              </>
            )}
          </Button>
        </div>

        {/* LaTeX Preview */}
        {showLatexPreview && (
          <div className="space-y-2">
            <h4 className="font-semibold text-foreground">Generated LaTeX Code:</h4>
            <Textarea
              value={latexContent}
              readOnly
              className="min-h-[300px] font-mono text-xs bg-muted"
              placeholder="LaTeX code will appear here..."
            />
            <p className="text-xs text-muted-foreground">
              This is the LaTeX code that will be sent to Overleaf. You can review it before exporting.
            </p>
          </div>
        )}

        {/* Export Info */}
        <div className="bg-gradient-accent p-4 rounded-lg">
          <h4 className="font-semibold text-accent-foreground mb-2">What happens when you export?</h4>
          <ul className="text-sm text-accent-foreground space-y-1">
            <li>• Your resume data is converted to professional LaTeX format</li>
            <li>• A new tab opens with your resume in Overleaf's editor</li>
            <li>• You can immediately edit the LaTeX code or compile to PDF</li>
            <li>• The resume uses the moderncv class for professional formatting</li>
            <li>• Your data stays private - nothing is stored on our servers</li>
          </ul>
        </div>

        {/* Requirements Check */}
        <div className="bg-muted p-4 rounded-lg">
          <h4 className="font-semibold text-foreground mb-2">Export Requirements:</h4>
          <div className="space-y-1 text-sm">
            <div className={`flex items-center gap-2 ${
              resumeData.personalInfo.fullName ? 'text-green-600' : 'text-destructive'
            }`}>
              <span>{resumeData.personalInfo.fullName ? '✓' : '✗'}</span>
              <span>Full Name {resumeData.personalInfo.fullName ? '(provided)' : '(required)'}</span>
            </div>
            <div className={`flex items-center gap-2 ${
              resumeData.personalInfo.email ? 'text-green-600' : 'text-destructive'
            }`}>
              <span>{resumeData.personalInfo.email ? '✓' : '✗'}</span>
              <span>Email Address {resumeData.personalInfo.email ? '(provided)' : '(required)'}</span>
            </div>
            <div className={`flex items-center gap-2 ${
              resumeData.education.length > 0 || resumeData.experience.length > 0 ? 'text-green-600' : 'text-orange-500'
            }`}>
              <span>{resumeData.education.length > 0 || resumeData.experience.length > 0 ? '✓' : '!'}</span>
              <span>Education or Experience {resumeData.education.length > 0 || resumeData.experience.length > 0 ? '(provided)' : '(recommended)'}</span>
            </div>
          </div>
        </div>

        {/* Help Text */}
        <div className="text-xs text-muted-foreground bg-muted p-3 rounded">
          <p className="mb-1">
            <strong>Need help with LaTeX?</strong> Once in Overleaf, you can switch to the Visual Editor 
            for a more user-friendly editing experience.
          </p>
          <p>
            <strong>Compilation issues?</strong> Visit{" "}
            <a 
              href="https://www.overleaf.com/contact" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              Overleaf Support
            </a>{" "}
            for assistance.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}